server:
  port: 8888
spring:
  application:
    name: config-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin.lab.pl
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///opt/microservices/config/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
