server:
  port: 8888
spring:
  application:
    name: config-service
  boot:
    admin:
      client:
        url: http://spring-admin-service/
        instance:
          name: spring-config-sba
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///tmp/microservices/config/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
