server:
  port: 8888
spring:
  application:
    name: config-service
  boot:
    admin:
      client:
        url: http://10.0.0.60:8762
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///tmp/microservices/config/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
