apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config
  labels:
    app: spring-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config
  template:
    metadata:
      labels:
        app: spring-config
    spec:
      containers:
        - name: spring-config
          image: bartoszbud/spring-config:DEV-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
